const translations = {
  "Home": "الرئيسية",
  "System": "النظام",
  "AI": "الذكاء الاصطناعي",
  "Results": "النتائج",
  "Team": "الفريق",
  "Research": "البحث",
  "Contact": "التواصل",
  "Get Involved": "شارك معنا",
  "System Overview": "نظرة عامة على النظام",
  "02 / SYSTEM OVERVIEW": "02 / نظرة عامة على النظام",
  "One System. Three Operational Layers.": "نظام واحد. ثلاث طبقات تشغيلية.",
  "Beta5G connects the factory traffic path to local Fog filtering, deeper Cloud classification, and a technical Dashboard view.": "يربط Beta5G مسار حركة المرور في المصنع بالترشيح المحلي عبر Fog والتصنيف المتعمق عبر Cloud وواجهة Dashboard التقنية.",
  "FACTORY / OT": "المصنع / OT",
  "Industrial traffic": "حركة مرور صناعية",
  "Generated records": "سجلات مُنشأة",
  "Local filtering": "ترشيح محلي",
  "Deep classification": "تصنيف متعمق",
  "Security visibility": "رؤية أمنية",
  "03 / THE FACTORY": "03 / المصنع",
  "04 / THE PROBLEM": "04 / المشكلة",
  "05 / THE SOLUTION": "05 / الحل",
  "06 / AI ENGINE": "06 / محرك الذكاء الاصطناعي",
  "07 / DATA & METHODOLOGY": "07 / البيانات والمنهجية",
  "08 / MODEL PERFORMANCE": "08 / أداء النماذج",
  "09 / LIVE SYSTEM TEST": "09 / اختبار النظام الحي",
  "10 / EXPLAINABLE AI": "10 / الذكاء الاصطناعي القابل للتفسير",
  "11 / INCIDENT RESPONSE": "11 / الاستجابة للحوادث",
  "12 / INDUSTRIAL IMPACT": "12 / الأثر الصناعي",
  "13 / LIMITATIONS & FUTURE": "13 / الحدود والآفاق المستقبلية",
  "14 / THE TEAM": "14 / الفريق",
  "15 / RESEARCH & DEMO": "15 / البحث والعرض",
  "16 / CONTACT & OPPORTUNITIES": "16 / التواصل والفرص",
  "Industrial Cybersecurity · AI Research": "الأمن السيبراني الصناعي · أبحاث الذكاء الاصطناعي",
  "A distributed, real-time intrusion detection system for smart factories that combines local Fog-based filtering with Cloud-based multi-class classification and explainable AI.": "نظام موزع وآني لكشف التسلل في المصانع الذكية، يجمع بين الترشيح المحلي عبر Fog والتصنيف متعدد الفئات عبر Cloud والذكاء الاصطناعي القابل للتفسير.",
  "Fog Filtering": "ترشيح Fog",
  "Cloud Classification": "تصنيف Cloud",
  "SHAP Explainability": "قابلية تفسير SHAP",
  "Explore the System": "استكشف النظام",
  "Watch Demo": "شاهد العرض",
  "Inside the Connected Factory": "داخل المصنع المتصل",
  "Industrial environment": "البيئة الصناعية",
  "Architecture": "البنية المعمارية",
  "STATUS: MONITORING": "الحالة: قيد المراقبة",
  "BETA5G SYSTEM": "نظام BETA5G",
  "System indicators": "مؤشرات النظام",
  "FACTORY / OT": "المصنع / OT",
  "DATA PATH": "مسار البيانات",
  "FOG NODE": "عقدة Fog",
  "DASHBOARD": "لوحة التحكم",
  "ANALYST VIEW": "واجهة المحلل",
  "Smart factories combine operational technology and information technology, creating heterogeneous environments where industrial devices continuously exchange network traffic.": "تجمع المصانع الذكية بين التكنولوجيا التشغيلية وتكنولوجيا المعلومات، فتنشئ بيئات متباينة تتبادل فيها الأجهزة الصناعية حركة الشبكة باستمرار.",
  "Why Traditional Detection Falls Short": "لماذا لا يكفي الكشف التقليدي؟",
  "Modern smart factories require security decisions in real time, but conventional IDS approaches create a gap between detection, explanation, and industrial context.": "تحتاج المصانع الذكية الحديثة إلى قرارات أمنية آنية، لكن أساليب IDS التقليدية تخلق فجوة بين الكشف والتفسير والسياق الصناعي.",
  "Cloud-Centric Detection": "الكشف المعتمد على Cloud",
  "Black-Box Decisions": "قرارات الصندوق الأسود",
  "IT-Oriented Benchmarks": "اختبارات معيارية موجهة لتكنولوجيا المعلومات",
  "Rare Attack Classes": "فئات الهجوم النادرة",
  "CLOUD-CENTRIC DETECTION": "الكشف المعتمد على Cloud",
  "BLACK-BOX DECISIONS": "قرارات الصندوق الأسود",
  "IT DATA ≠ INDUSTRIAL CONTEXT": "بيانات تقنية المعلومات ≠ السياق الصناعي",
  "ANALYTICAL FRAME": "إطار تحليلي",
  "From Detection to Explanation": "من الكشف إلى التفسير",
  "TRAFFIC GENERATION": "توليد حركة المرور",
  "LOCAL FILTERING": "الترشيح المحلي",
  "DEEP CLASSIFICATION": "التصنيف المتعمق",
  "TECHNICAL MONITORING": "المراقبة التقنية",
  "OBSERVER INTERFACE": "واجهة المراقب",
  "THE KEY DESIGN IDEA": "الفكرة التصميمية الأساسية",
  "LOCAL": "محلي",
  "DEEP": "متعمق",
  "EXPLAINABLE": "قابل للتفسير",
  "From Network Flows to Model-Ready Data": "من تدفقات الشبكة إلى بيانات جاهزة للنموذج",
  "Measured Performance": "الأداء المقاس",
  "Table 1. Measured model performance": "الجدول 1. أداء النماذج المقاس",
  "Model": "النموذج",
  "Role": "الدور",
  "Accuracy": "الدقة",
  "Recall": "الاستدعاء",
  "FOG PERFORMANCE HIGHLIGHT": "أبرز أداء Fog",
  "MISSED-ATTACK COMPARISON": "مقارنة الهجمات الفائتة",
  "CLOUD PERFORMANCE": "أداء Cloud",
  "480 Packets. One Live Stress Test.": "480 حزمة. اختبار إجهاد حي واحد.",
  "A live stress test evaluated the deployed system under mixed normal and attack traffic, measuring detection and Fog filtering behavior.": "قيّم اختبار إجهاد حي النظام المنشور تحت حركة مرور مختلطة طبيعية وهجومية، وقاس سلوك الكشف والترشيح في Fog.",
  "Why Did the Model Flag It?": "لماذا صنّف النموذج الحزمة كتهديد؟",
  "INCIDENT QUEUE": "قائمة الحوادث",
  "SHAP FORENSICS": "التحليل الجنائي عبر SHAP",
  "INCIDENT METADATA": "بيانات الحادثة الوصفية",
  "FEATURE CONTRIBUTION": "مساهمة الخصائص",
  "ATTACK": "هجوم",
  "NORMAL": "طبيعي",
  "ACTIONABLE FORENSICS": "تحليل جنائي قابل للتنفيذ",
  "Detection is only the first decision. Beta5G uses SHAP to make the Cloud classification interpretable and auditable.": "الكشف هو القرار الأول فقط. يستخدم Beta5G تقنية SHAP لجعل تصنيف Cloud قابلاً للتفسير والتدقيق.",
  "SELECT AN INCIDENT": "اختر حادثة",
  "FOR FORENSIC ANALYSIS": "للتحليل الجنائي الرقمي",
  "From Detection to Decision.": "من الكشف إلى القرار.",
  "DECISION REQUIRED": "قرار مطلوب",
  "RESPONSE STATUS": "حالة الاستجابة",
  "AWAITING ACTION": "بانتظار الإجراء",
  "Once an incident reaches the Cloud layer and is classified, Beta5G provides a structured interface for security personnel to decide how the incident should be handled.": "عندما تصل الحادثة إلى طبقة Cloud ويتم تصنيفها، يوفر Beta5G واجهة منظمة ليقرر أفراد الأمن كيفية التعامل معها.",
  "Built for the Reality of the Factory Floor.": "مصمم لواقع أرضية المصنع.",
  "FACTORY FLOOR": "أرضية المصنع",
  "LOCAL FOG NODE": "عقدة Fog محلية",
  "CLOUD ANALYSIS": "تحليل Cloud",
  "SECURITY VISIBILITY": "الرؤية الأمنية",
  "WHY IT MATTERS": "لماذا يهم ذلك",
  "USER VISIBILITY": "رؤية المستخدم",
  "Research With Clear Boundaries.": "بحث بحدود واضحة.",
  "CURRENT LIMITATIONS": "الحدود الحالية",
  "FUTURE RESEARCH DIRECTIONS": "اتجاهات البحث المستقبلية",
  "RESEARCH ROADMAP": "خارطة طريق البحث",
  "Built by a Research Team.": "بُني بواسطة فريق بحثي.",
  "ACADEMIC SUPERVISOR": "المشرف الأكاديمي",
  "CORE TEAM": "الفريق الأساسي",
  "Academic Supervisor": "المشرف الأكاديمي",
  "Team Leader": "قائد الفريق",
  "Designer": "مصمم",
  "See the Research. Run the Demo.": "اطّلع على البحث وشغّل العرض.",
  "01 / RESEARCH PAPER": "01 / البحث العلمي",
  "02 / SYSTEM DEMO": "02 / عرض النظام",
  "03 / SOURCE / PROJECT": "03 / المصدر / المشروع",
  "READ RESEARCH": "اقرأ البحث",
  "DOWNLOAD PDF": "تنزيل PDF",
  "WATCH DEMO": "شاهد العرض",
  "SOURCE / PROJECT": "المصدر / المشروع",
  "Explore the research paper and the system demonstration behind Beta5G.": "استكشف البحث العلمي وعرض النظام وراء Beta5G.",
  "Protecting a Factory from Cyberattacks Using Artificial Intelligence": "حماية مصنع من الهجمات السيبرانية باستخدام الذكاء الاصطناعي",
  "Let’s Build What Comes Next.": "لنبنِ ما سيأتي تالياً.",
  "RESEARCH COLLABORATION": "التعاون البحثي",
  "INDUSTRIAL PARTNERSHIPS": "الشراكات الصناعية",
  "INTERNSHIP OPPORTUNITIES": "فرص التدريب",
  "TECHNICAL OPPORTUNITIES": "الفرص التقنية",
  "GRADUATE OPPORTUNITIES": "فرص الدراسات العليا",
  "Beta5G is open to research collaboration, industrial evaluation, technical opportunities, and future development.": "يرحب Beta5G بالتعاون البحثي والتقييم الصناعي والفرص التقنية والتطوير المستقبلي.",
  "Research. Detect. Explain.": "ابحث. اكشف. فسّر.",
  "Explore the system and connect with the team.": "استكشف النظام وتواصل مع الفريق.",
  "Email": "البريد الإلكتروني",
  "Other contact method": "طريقة تواصل أخرى",
  "No public contact details are published in the current project.": "لا توجد بيانات تواصل عامة منشورة في المشروع الحالي.",
  "Contact the team or supervisor directly for project communication.": "تواصل مباشرة مع الفريق أو المشرف بشأن المشروع.",
  "Hakam Zakaria Taha": "حكم زكريا طه",
  "Hassan Hussein Naser": "حسن حسين ناصر",
  "Supervisor Mohammed Zaki Hasan": "المشرف محمد زكي حسن",
  "Main navigation": "التنقل الرئيسي",
  "Language selector": "اختيار اللغة",
  "Team photo placeholder": "عنصر نائب لصورة عضو الفريق",
  "Beta5G system demonstration video": "فيديو عرض نظام Beta5G",
  "Three Models. Two Decisions. One Explainable Pipeline.": "ثلاثة نماذج. قراران. خط أنابيب واحد قابل للتفسير.",
  "This is a research prototype for industrial cybersecurity.": "هذا نموذج بحثي للأمن السيبراني الصناعي.",
  "RESEARCH · ENGINEERING · COMMUNICATION": "البحث · الهندسة · التواصل",
  "RESEARCH · AI · SYSTEMS": "البحث · الذكاء الاصطناعي · الأنظمة",
  "Research development, technical documentation, and research paper writing": "تطوير البحث والتوثيق الفني وكتابة الورقة البحثية",
  "Project coordination and team leadership": "تنسيق المشروع وقيادة الفريق",
  "Project source link will be added when an official repository URL is available.": "سيتم إضافة رابط مصدر المشروع عندما يصبح عنوان مستودع رسمي متاحًا.",
  "GITHUB / PROJECT URL · PLACEHOLDER": "GitHub / رابط المشروع · عنصر مؤقت",
  "Team photo placeholder": "عنصر نائب لصورة الموظف",
  "Current limitations": "القيود الحالية",
  "Future research directions": "اتجاهات البحث المستقبلية",
  "Research prototype": "نموذج بحثي",
  "Research and Development": "البحث والتطوير",
  "Alpha system": "نظام تجريبي",
  "Industrial cybersecurity research": "أبحاث الأمن السيبراني الصناعي",
  "Factory floor": "أرضية المصنع",
  "Low-latency response": "استجابة منخفضة التأخير",
  "System information": "معلومات النظام",
  "Incident analysis": "تحليل الحوادث",
  "Noise ±40%": "ضجيج ±40%",
  "slowdown ×10": "تأخير ×10",
  "padding": "التعبئة",
  "SMOTE": "SMOTE",
  "minority classes": "الفئات الأقلية",
  "target ≥ 5,000 samples per class": "الهدف ≥ 5000 عينة لكل فئة",
  "System overview": "نظرة عامة على النظام",
  "Security personnel": "أفراد الأمن",
  "Technical managers": "المديرون التقنيون",
  "NO PUBLIC CONTACT DETAILS": "لا توجد تفاصيل تواصل عامة",
  "Research. Detect. Explain": "ابحث. اكتشف. فسّر",
  "Ready to explore": "جاهز للاستكشاف",
  "Your browser does not support HTML5 video.": "متصفحك لا يدعم الفيديو من HTML5.",
  "Team photo placeholder": "عنصر نائب لصورة عضو الفريق",
  "Team member": "عضو الفريق",
  "BETA5G": "BETA5G",
  "Industrial Cybersecurity": "الأمن السيبراني الصناعي",
  "AI Research": "أبحاث الذكاء الاصطناعي",
  "Project coordination": "تنسيق المشروع",
  "System development": "تطوير النظام",
  "Visual design": "التصميم البصري",
  "Academic supervision": "الإشراف الأكاديمي",
  "Research and system development": "البحث وتطوير النظام",
  "Bilingual interface": "واجهة ثنائية اللغة",
  "Security collaboration": "التعاون الأمني",
  "This is a static interface preview": "هذه معاينة واجهة ثابتة",
  "Static interface context. Incident records are not populated here.": "سياق واجهة ثابتة. لا توجد سجلات الحوادث مُعبأة هنا.",
  "Abstract directional bars. No SHAP scores or ranking are reported here.": "أشرطة اتجاهية مجردة. لا توجد درجات أو ترتيب SHAP مُعلن هنا.",
  "Figure": "شكل",
  "Table": "جدول",
  "Protecting a Factory from Cyberattacks Using Artificial Intelligence": "حماية مصنع من الهجمات السيبرانية باستخدام الذكاء الاصطناعي",
  "DETECT": "اكتشف",
  "CLASSIFY": "صنّف",
  "EXPLAIN": "فسّر",
  "Fog Filtering": "ترشيح Fog",
  "Cloud Classification": "تصنيف Cloud",
  "SHAP Explainability": "قابلية تفسير SHAP",
  "TRAFFIC SIMULATOR": "محاكي حركة المرور",
  "OT NETWORK": "شبكة OT",
  "MONITORING": "قيد المراقبة",
  "INDUSTRIAL CYBERSECURITY · AI RESEARCH": "الأمن السيبراني الصناعي · أبحاث الذكاء الاصطناعي",
  "Industrial Cybersecurity": "الأمن السيبراني الصناعي",
  "AI Research": "أبحاث الذكاء الاصطناعي",
  "The Detection Gap": "فجوة الكشف",
  "THE DETECTION GAP": "فجوة الكشف",
  "OT + IT CONVERGENCE": "التقارب بين OT وIT",
  "Industrial systems increasingly combine operational technology with information technology.": "تجمع الأنظمة الصناعية بين التكنولوجيا التشغيلية وتكنولوجيا المعلومات بشكل متزايد.",
  "The detection gap": "فجوة الكشف",
  "THE KEY DESIGN IDEA": "الفكرة التصميمية الأساسية",
  "Traffic Generation": "توليد الحركة",
  "Local Filtering": "الترشيح المحلي",
  "Deep Classification": "التصنيف العميق",
  "Technical Monitoring": "المراقبة التقنية",
  "Observer Interface": "واجهة المراقب",
  "From Detection to Explanation": "من الكشف إلى التفسير",
  "Beta5G separates fast local traffic filtering from deeper cloud-based attack classification and explainability.": "يفصل Beta5G بين الترشيح السريع للمحلي لحركة المرور وبين تصنيف الهجمات الأعمق في السحابة وقابلية التفسير.",
  "Three Models. Two Decisions. One Explainable Pipeline.": "ثلاثة نماذج. قراران. خط أنابيب واحد قابل للتفسير.",
  "Beta5G separates lightweight local detection from deeper multi-class analysis, using SHAP to make the final decision interpretable to security operators.": "يفصل Beta5G بين الكشف المحلي الخفيف والتحليل المتعدد الفئات الأعمق، مستخدمًا SHAP لجعل القرار النهائي قابلاً للتفسير لأفراد الأمن.",
  "NETWORK PACKET": "حزمة الشبكة",
  "ESCALATED TRAFFIC": "حركة مرور مُحالة",
  "FOG": "Fog",
  "BINARY FILTER": "مرشح ثنائي",
  "Decision Tree v3": "شجرة القرار v3",
  "Isolation Forest": "غابة العزل (Isolation Forest)",
  "trained exclusively on normal traffic": "مدرّب فقط على حركة المرور الطبيعية",
  "BINARY DECISION": "قرار ثنائي",
  "NORMAL vs SUSPICIOUS": "طبيعي مقابل مشتبه به",
  "CLOUD": "Cloud",
  "MULTI-CLASS ANALYSIS": "تحليل متعدد الفئات",
  "XGBOOST v3": "XGBoost v3",
  "ATTACK TYPE": "نوع الهجوم",
  "SHAP": "SHAP",
  "EXPLAINABLE AI": "ذكاء اصطناعي قابل للتفسير",
  "TREEEXPLAINER": "TreeExplainer",
  "FEATURE CONTRIBUTIONS": "مساهمات الخصائص",
  "OPERATOR EXPLANATION": "تفسير المشغل",
  "STAGE 01": "المرحلة 01",
  "STAGE 02": "المرحلة 02",
  "STAGE 03": "المرحلة 03",
  "BINARY FILTERING": "الترشيح الثنائي",
  "MULTI-CLASS CLASSIFICATION": "التصنيف متعدد الفئات",
  "Human-interpretable model decision": "قرار النموذج القابل للتفسير للبشر",
  "Why Did the Model Flag It?": "لماذا أشار النموذج إلى ذلك؟",
  "Detection is only the first decision. Beta5G uses SHAP to make the Cloud classification interpretable and auditable.": "الكشف ليس سوى القرار الأول. يستخدم Beta5G SHAP لجعل تصنيف Cloud قابلاً للتفسير والمراجعة.",
  "INCIDENT MANAGER": "مدير الحوادث",
  "REPRESENTATIONAL WORKFLOW INTERFACE": "واجهة سير عمل تمثيلية",
  "CONTINUE OBSERVATION": "استمرار المراقبة",
  "Select the response action that matches the operator's assessment. Actions are shown as decision options, not automated commands.": "اختر إجراء الاستجابة الذي يطابق تقييم المشغل. تُعرض الإجراءات كخيارات قرار، لا أوامر آلية.",
  "ISOATE": "عزل",
  "ISOLATE": "عزل",
  "MONITOR": "مراقبة",
  "IGNORE": "تجاهل",
  "ESCALATE": "رفع",
  "RESEARCH CONTEXT": "سياق البحث",
  "Beta5G connects detection, classification, explanation, and operator response into a single security workflow.": "يربط Beta5G بين الكشف والتصنيف والتفسير واستجابة المشغل في سير عمل أمني واحد.",
  "Built for the Reality of the Factory Floor.": "مصمم لواقع أرضية المصنع.",
  "Beta5G is designed for small and medium industrial facilities where detection speed, local processing, explainability, and operational simplicity matter.": "تم تصميم Beta5G للمؤسسات الصناعية الصغيرة والمتوسطة حيث تهم سرعة الكشف والمعالجة المحلية وقابلية التفسير والبساطة التشغيلية.",
  "LOCAL DETECTION": "الكشف المحلي",
  "LOW-LATENCY RESPONSE": "استجابة منخفضة التأخير",
  "SCALABLE ARCHITECTURE": "بنية قابلة للتوسع",
  "OPERATIONAL VISIBILITY": "الرؤية التشغيلية",
  "WHY IT MATTERS": "لماذا يهم هذا؟",
  "HORIZONTAL FOG SCALING": "التوسع الأفقي لـ Fog",
  "Production Line": "خط الإنتاج",
  "Technical View": "العرض التقني",
  "Observer View": "عرض المراقب",
  "Bilingual interface": "واجهة ثنائية اللغة",
  "FIRST-STAGE PROCESSING": "المعالجة في المرحلة الأولى",
  "Read Paper": "اقرأ الورقة",
  "READ THE PAPER": "اقرأ الورقة",
  "Watch the Demo": "شاهد العرض",
  "READ RESEARCH": "اقرأ البحث",
  "DOWNLOAD PDF": "تنزيل PDF",
  "READ THE PAPER": "اقرأ الورقة",
  "WATCH THE DEMO": "شاهد العرض",
  "General / Research": "عام / بحث",
  "System demonstration": "عرض النظام",
  "beta5g-website": "beta5g-website",
  "Project URL placeholder": "عنصر مؤقت لعنوان المشروع",
  "Research. Detect. Explain.": "ابحث. اكتشف. فسّر.",
  "Explore the system and connect with the team.": "استكشف النظام وتواصل مع الفريق.",
  "No public contact details are published in the current project.": "لا توجد تفاصيل تواصل عامة منشورة في المشروع الحالي.",
  "placeholder": "عنصر مؤقت",
  "Team photo placeholder": "عنصر نائب لصورة عضو الفريق",
  "Project coordination": "تنسيق المشروع",
  "System development": "تطوير النظام",
  "Visual design": "التصميم البصري",
  "Academic supervision": "الإشراف الأكاديمي",
  "Research and system development": "البحث وتطوير النظام",
  "Security collaboration": "التعاون الأمني",
  "This is a static interface preview": "هذه معاينة واجهة ثابتة",
  "Static interface context. Incident records are not populated here.": "سياق واجهة ثابتة. لا توجد سجلات الحوادث مُعبأة هنا.",
  "Abstract directional bars. No SHAP scores or ranking are reported here.": "أشرطة اتجاهية مجردة. لا توجد درجات أو ترتيب SHAP معروض هنا.",
  "PROJECT SOURCE": "مصدر المشروع",
  "Research / Demo": "البحث / العرض",
  "Contact / Opportunities": "التواصل / الفرص",
  "Current limitations": "القيود الحالية",
  "Future research directions": "اتجاهات البحث المستقبلية",
  "Where Beta5G goes next": "أين يتجه Beta5G بعد ذلك",
  "Research With Clear Boundaries.": "بحث بحدود واضحة.",
  "Built by a Research Team.": "بني بواسطة فريق بحثي.",
  "protecting a factory": "حماية مصنع",
  "Research with clear boundaries": "بحث بحدود واضحة",
  "AUDIO": "صوت",
  "VIDEO": "فيديو",
  "Project source": "مصدر المشروع",
  "Official project repository.": "المستودع الرسمي للمشروع.",
  "VIEW SOURCE ON GITHUB": "عرض المصدر على GitHub",
  "localStorage": "localStorage",
  "Language selector": "اختيار اللغة",
  "Detection process": "عملية الكشف",
  "Process labels": "تسميات العملية",
  "Technical system status": "حالة النظام التقنية",
  "Beta5G system preview": "معاينة نظام Beta5G",
  "Industrial control environment": "بيئة التحكم الصناعية",
  "Industrial technology convergence": "تقارب التكنولوجيا الصناعية",
  "Factory network diagram": "مخطط شبكة المصنع",
  "Industrial network": "الشبكة الصناعية",
  "Security monitoring status": "حالة المراقبة الأمنية",
  "Industrial protocol channels": "قنوات البروتوكولات الصناعية",
  "The detection gap": "فجوة الكشف",
  "Four independent challenges shape the research problem.": "تشكّل أربعة تحديات مستقلة مشكلة البحث.",
  "Processing traffic primarily through the cloud can introduce latency that is incompatible with real-time OT requirements.": "قد تؤدي معالجة حركة المرور بشكل أساسي عبر Cloud إلى زمن استجابة لا يتوافق مع متطلبات OT الآنية.",
  "A detection result alone is not enough for a security operator. Black-box models provide no actionable explanation for why a packet was classified as an attack.": "لا تكفي نتيجة الكشف وحدها لمسؤول الأمن. فالنماذج الصندوقية لا تقدم تفسيرًا عمليًا يوضح سبب تصنيف الحزمة كهجوم.",
  "Many intrusion-detection benchmarks are based on IT-oriented traffic and do not fully represent industrial protocol characteristics.": "تعتمد كثير من معايير كشف التسلل على حركة مرور موجهة لتقنية المعلومات، ولا تمثل بالكامل خصائص البروتوكولات الصناعية.",
  "RARE ATTACK CLASSES": "فئات الهجوم النادرة",
  "Severe class imbalance can make rare but critical attacks difficult to detect reliably.": "قد يجعل الاختلال الشديد في توازن الفئات اكتشاف الهجمات النادرة والحرجة بشكل موثوق أمرًا صعبًا.",
  "SIMULATOR": "المحاكي",
  "Generates synthetic network records every 0.5 seconds.": "ينشئ سجلات شبكة اصطناعية كل 0.5 ثانية.",
  "15% attack probability": "احتمال هجوم بنسبة 15%",
  "Either model flag escalates the packet to Cloud.": "يؤدي اكتشاف أي من النموذجين إلى تصعيد الحزمة إلى Cloud.",
  "LOCAL FILTER": "الترشيح المحلي",
  "DEEP ANALYSIS": "التحليل المتعمق",
  "ESCALATED PACKET": "الحزمة المصعّدة",
  "ATTACK TYPE": "نوع الهجوم",
  "Multi-class classification across 9 attack categories.": "تصنيف متعدد الفئات عبر 9 فئات من الهجمات.",
  "Primary real-time monitoring interface for technical managers.": "واجهة المراقبة الآنية الرئيسية للمديرين التقنيين.",
  "Simplified bilingual Arabic/English interface for floor supervisors and shift managers.": "واجهة مبسطة ثنائية اللغة بالعربية والإنجليزية لمشرفي أرضية المصنع ومديري الورديات.",
  "ASSOCIATED MONITORING LAYER": "طبقة المراقبة المرتبطة",
  "Fog handles lightweight binary filtering close to the traffic.": "يتولى Fog الترشيح الثنائي الخفيف بالقرب من حركة المرور.",
  "Cloud performs multi-class classification on escalated traffic.": "ينفذ Cloud التصنيف متعدد الفئات لحركة المرور المصعّدة.",
  "SHAP provides human-interpretable explanations.": "يوفر SHAP تفسيرات يفهمها البشر.",
  "DOCKER COMPOSE": "Docker Compose",
  "factory_network": "factory_network",
  "HTTP COMMUNICATION": "اتصال HTTP",
  "MULTI-CLASS DECISION": "قرار متعدد الفئات",
  "EXPLAINABLE AI · TREEEXPLAINER": "ذكاء اصطناعي قابل للتفسير · TreeExplainer",
  "Normal vs. Suspicious": "طبيعي مقابل مشتبه به",
  "9 attack categories": "9 فئات من الهجمات",
  "EXPLANATION": "التفسير",
  "TRAINING HARDENING": "تعزيز التدريب",
  "ADVERSARIAL AUGMENTATION": "الزيادة العدائية",
  "noise ±40% · slowdown ×10 · padding": "ضجيج ±40% · إبطاء ×10 · حشو",
  "minority classes · target ≥ 5,000 samples per class": "الفئات الأقلية · الهدف ≥ 5000 عينة لكل فئة",
  "FEATURE SPACE": "حيز الخصائص",
  "42 RAW FEATURES": "42 خاصية خام",
  "8 DERIVED FEATURES": "8 خصائص مشتقة",
  "Beta5G uses the UNSW-NB15 dataset and a structured training pipeline combining categorical encoding, feature engineering, adversarial augmentation, and SMOTE oversampling.": "يستخدم Beta5G مجموعة بيانات UNSW-NB15 وخط تدريب منظمًا يجمع بين ترميز الفئات وهندسة الخصائص والزيادة العدائية وأخذ العينات الزائد باستخدام SMOTE.",
  "DATASET OVERVIEW": "نظرة عامة على مجموعة البيانات",
  "TRAINING RECORDS": "سجلات التدريب",
  "TESTING RECORDS": "سجلات الاختبار",
  "RAW FEATURES": "خصائص خام",
  "CLASSES": "فئات",
  "Raw network-flow characteristics include duration, byte counts, packet counts, TTL values, TCP flags, and connection-tracking counters.": "تشمل خصائص تدفق الشبكة الخام المدة وعدد وحدات البايت وعدد الحزم وقيم TTL وأعلام TCP وعدادات تتبع الاتصالات.",
  "FEATURE ENGINEERING": "هندسة الخصائص",
  "42 raw features + 8 derived features": "42 خاصية خام + 8 خصائص مشتقة",
  "Eight derived ratio and behavior features were appended to the original feature set. They amplify asymmetric traffic patterns characteristic of DoS and reconnaissance attacks, supported by XGBoost importance scores.": "أضيفت ثماني خصائص مشتقة للنسب والسلوك إلى مجموعة الخصائص الأصلية. وهي تعزز أنماط حركة المرور غير المتماثلة المميزة لهجمات DoS والاستطلاع، بدعم من درجات أهمية XGBoost.",
  "TRAINING PIPELINE": "خط التدريب",
  "SEPARATE FROM RUNTIME INFERENCE": "منفصل عن الاستدلال أثناء التشغيل",
  "source records": "السجلات المصدرية",
  "LABEL ENCODING": "ترميز التسميات",
  "proto · service · state → model-ready representation": "proto · service · state ← تمثيل جاهز للنموذج",
  "3× attack copies: noise ±40% · slowdown ×10 · padding": "3× نسخ من الهجوم: ضجيج ±40% · إبطاء ×10 · حشو",
  "minority classes below 5,000 → ≥ 5,000 samples per class": "الفئات الأقلية الأقل من 5000 ← ≥ 5000 عينة لكل فئة",
  "MODEL TRAINING": "تدريب النموذج",
  "prepared training representation": "تمثيل تدريب مُجهز",
  "01 / LABEL ENCODING": "01 / ترميز التسميات",
  "Saved LabelEncoders are reused during inference.": "يعاد استخدام LabelEncoders المحفوظة أثناء الاستدلال.",
  "RARE CLASSES": "الفئات النادرة",
  "Attack sub-types such as Worms and Shellcode: fewer than 0.05% of UNSW-NB15.": "أنواع فرعية من الهجمات مثل Worms وShellcode: أقل من 0.05% من UNSW-NB15.",
  "DATASET SCOPE": "نطاق مجموعة البيانات",
  "UNSW-NB15 does not include Modbus- or MQTT-specific attack vectors. Therefore, protocol-level OT attacks rely on anomaly detection rather than supervised classification.": "لا تتضمن UNSW-NB15 متجهات هجوم خاصة بـ Modbus أو MQTT. لذلك تعتمد هجمات OT على مستوى البروتوكول على كشف الشذوذ بدلًا من التصنيف الخاضع للإشراف.",
  "The evaluation compares the Fog binary filtering models and Cloud multi-class classifiers across the training versions reported in the research paper.": "تقارن الدراسة نماذج الترشيح الثنائي في Fog ومصنفات Cloud متعددة الفئات عبر إصدارات التدريب المذكورة في الورقة البحثية.",
  "Decision Tree v1": "شجرة القرار v1",
  "Random Forest": "الغابة العشوائية",
  "ROLE": "الدور",
  "ACC": "الدقة",
  "RECALL": "الاستدعاء",
  "attacks evaluated": "هجمات جرى تقييمها",
  "missed": "فائتة",
  "FNR": "معدل النتائج السلبية الكاذبة",
  "14× improvement in missed-attack count over DT v1's 765 missed attacks.": "تحسن بمقدار 14× في عدد الهجمات الفائتة مقارنة بـ 765 هجومًا فائتًا في DT v1.",
  "missed attacks": "هجمات فائتة",
  "14× fewer missed attacks": "هجمات فائتة أقل بمقدار 14×",
  "Multi-class attack classification": "تصنيف متعدد الفئات للهجمات",
  "accuracy": "الدقة",
  "The Cloud models perform multi-class attack classification; measured XGBoost v3 accuracy is 76.15%.": "تنفذ نماذج Cloud تصنيفًا متعدد الفئات للهجمات؛ وبلغت دقة XGBoost v3 المقاسة 76.15%.",
  "XGBOOST V3 · CONFUSION-MATRIX CONTEXT": "XGBOOST V3 · سياق مصفوفة الالتباس",
  "correct": "صحيح",
  "SCIENTIFIC INTERPRETATION": "التفسير العلمي",
  "The Fog model prioritizes attack recall to minimize missed attacks before escalation.": "يعطي نموذج Fog الأولوية لاستدعاء الهجمات لتقليل الهجمات الفائتة قبل التصعيد.",
  "The Cloud model performs deeper multi-class classification on escalated traffic. These metrics measure different tasks.": "ينفذ نموذج Cloud تصنيفًا أعمق متعدد الفئات لحركة المرور المصعّدة. وتقيس هذه المؤشرات مهام مختلفة.",
  "FOG · DT v3 · 99.89% recall": "FOG · DT v3 · استدعاء 99.89%",
  "CLOUD · XGBoost v3 · 76.15% accuracy": "CLOUD · XGBoost v3 · دقة 76.15%",
  "is the Fog anomaly detector with reported recall ≈62%, not an overall system detection rate.": "هو كاشف الشذوذ في Fog باستدعاء مُبلغ عنه يبلغ ≈62%، وليس معدل كشف النظام ككل.",
  "TRAFFIC IN": "حركة المرور الداخلة",
  "MIXED PACKETS": "حزم مختلطة",
  "FOG FILTERING": "ترشيح Fog",
  "LOCAL FILTER": "ترشيح محلي",
  "DEPLOYED SYSTEM STAGE": "مرحلة النظام المنشور",
  "DETECTION": "الكشف",
  "DETECTED": "مكتشفة",
  "RESULT": "النتيجة",
  "DETECTION RATE": "معدل الكشف",
  "TOTAL PACKETS": "إجمالي الحزم",
  "NOT DETECTED": "غير مكتشفة",
  "derived: 480 − 469": "مشتقة: 480 − 469",
  "FOG FILTER RATE": "معدل ترشيح Fog",
  "The reported Fog filter rate demonstrates that only a small portion of the mixed traffic was filtered locally while the system maintained a 97.7% detection rate in the live stress test.": "يوضح معدل ترشيح Fog المُبلغ عنه أن جزءًا صغيرًا فقط من حركة المرور المختلطة رُشّح محليًا، بينما حافظ النظام على معدل كشف قدره 97.7% في اختبار الإجهاد الحي.",
  "MODEL PERFORMANCE": "أداء النموذج",
  "VERSUS": "مقابل",
  "LIVE SYSTEM TEST": "اختبار النظام الحي",
  "RESPONSE CONTEXT": "سياق الاستجابة",
  "SUB-SECOND RESPONSE": "استجابة أقل من ثانية",
  "Reported in the live-system evaluation.": "مُبلغ عنها في تقييم النظام الحي.",
  "ARCHITECTURE / IMPACT CONTEXT": "سياق البنية / الأثر",
  "DESCRIBED DEPLOYMENT LATENCY": "زمن الاستجابة الموصوف للنشر",
  "Targeted/achieved deployment latency described for Fog nodes co-located with factory floor switches.": "زمن استجابة النشر المستهدف/المحقق الموصوف لعقد Fog الموجودة بجوار محولات أرضية المصنع.",
  "FORENSIC WORKSPACE": "مساحة العمل الجنائية الرقمية",
  "EXPLAINABLE CLASSIFICATION FOR AUDITABLE INCIDENT ANALYSIS": "تصنيف قابل للتفسير لتحليل حوادث قابل للتدقيق",
  "NETWORK EVENT": "حدث شبكي",
  "CLOUD CLASSIFICATION": "تصنيف Cloud",
  "SHAP EXPLANATION": "تفسير SHAP",
  "Incident ID": "معرّف الحادثة",
  "Not populated": "غير مُعبأ",
  "Source Device": "الجهاز المصدر",
  "Risk Level": "مستوى الخطورة",
  "RF Confidence Score": "درجة ثقة RF",
  "Detection Timestamp": "الطابع الزمني للكشف",
  "CONTRIBUTION DIRECTION ONLY": "اتجاه المساهمة فقط",
  "Feature contribution": "مساهمة الخاصية",
  "FORENSIC INTERPRETATION": "التفسير الجنائي الرقمي",
  "SHAP shows how individual features influence the model's classification decision, turning a black-box prediction into an interpretable forensic signal.": "يوضح SHAP كيف تؤثر الخصائص الفردية في قرار تصنيف النموذج، محولًا التنبؤ الصندوقي إلى إشارة جنائية رقمية قابلة للتفسير.",
  "XGBoost performs multi-class attack classification in the Cloud layer.": "ينفذ XGBoost تصنيفًا متعدد الفئات للهجمات في طبقة Cloud.",
  "SHAP / TreeExplainer decomposes the model decision into feature contributions.": "يفكك SHAP / TreeExplainer قرار النموذج إلى مساهمات للخصائص.",
  "INTERPRET": "فسّر",
  "Security personnel can inspect which feature signals pushed the decision toward attack or normal.": "يمكن لأفراد الأمن فحص إشارات الخصائص التي دفعت القرار نحو الهجوم أو الحالة الطبيعية.",
  "CLOUD MODEL CONTEXT": "سياق نموذج Cloud",
  "Explanation: SHAP / TreeExplainer": "التفسير: SHAP / TreeExplainer",
  "ENGINEERED FEATURES AVAILABLE TO THE PIPELINE": "الخصائص المشتقة المتاحة لخط المعالجة",
  "FOG DETECTION": "كشف Fog",
  "CLOUD CLASSIFICATION": "تصنيف Cloud",
  "SHAP EXPLANATION": "تفسير SHAP",
  "SECURITY DECISION": "قرار أمني",
  "CLASSIFICATION · ATTACK": "التصنيف · هجوم",
  "Select the response action that matches the operator's assessment. Actions are shown as decision options, not automated commands.": "اختر إجراء الاستجابة الذي يطابق تقييم المشغل. تُعرض الإجراءات كخيارات قرار، لا أوامر آلية.",
  "Separate the affected asset from the operational environment when containment is required.": "افصل الأصل المتأثر عن البيئة التشغيلية عند الحاجة إلى الاحتواء.",
  "Continue observation when the incident requires additional operational context.": "واصل المراقبة عندما تتطلب الحادثة سياقًا تشغيليًا إضافيًا.",
  "Dismiss the incident when the security operator determines that no further action is required.": "تجاهل الحادثة عندما يقرر مسؤول الأمن عدم الحاجة إلى إجراء إضافي.",
  "Raise the incident for additional security or operational attention.": "صعّد الحادثة لمزيد من الاهتمام الأمني أو التشغيلي.",
  "Process network traffic close to the factory floor through Fog-based filtering.": "عالج حركة مرور الشبكة بالقرب من أرضية المصنع عبر الترشيح القائم على Fog.",
  "Detection latency in the described co-located Fog deployment.": "زمن الكشف في نشر Fog المتجاور الموصوف.",
  "Add Fog nodes as production lines or monitored areas expand.": "أضف عقد Fog مع توسع خطوط الإنتاج أو المناطق المراقبة.",
  "Provide technical and observer-oriented dashboards for different users.": "وفر لوحات تحكم موجهة للمستخدمين التقنيين والمراقبين.",
  "Designed for facilities without a dedicated SOC.": "مصمم للمنشآت التي لا تملك مركز عمليات أمنية مخصصًا.",
  "Keep raw traffic processing close to the operational environment.": "أبقِ معالجة حركة المرور الخام قريبة من البيئة التشغيلية.",
  "Separate deep AI analysis from local first-stage filtering.": "افصل تحليل الذكاء الاصطناعي المتعمق عن الترشيح المحلي في المرحلة الأولى.",
  "Give technical and non-technical personnel appropriate visibility.": "امنح الأفراد التقنيين وغير التقنيين رؤية مناسبة.",
  "PRODUCTION LINE 01": "خط الإنتاج 01",
  "PRODUCTION LINE 02": "خط الإنتاج 02",
  "PRODUCTION LINE 03": "خط الإنتاج 03",
  "LOCAL PROCESSING": "المعالجة المحلية",
  "First-stage processing occurs locally at the Fog layer; suspicious traffic can then be forwarded to the Cloud for deeper classification.": "تحدث المعالجة في المرحلة الأولى محليًا في طبقة Fog؛ ثم يمكن إرسال حركة المرور المشتبه بها إلى Cloud لتصنيف أعمق.",
  "Fog filtering keeps the first-stage analysis close to the factory environment, reducing the need to transmit raw traffic off-site.": "يبقي ترشيح Fog التحليل في المرحلة الأولى قريبًا من بيئة المصنع، مما يقلل الحاجة إلى نقل حركة المرور الخام خارج الموقع.",
  "TECHNICAL VIEW": "العرض التقني",
  "For technical security personnel": "لأفراد الأمن التقنيين",
  "OBSERVER VIEW": "عرض المراقب",
  "For floor supervisors / shift managers": "لمشرفي أرضية المصنع / مديري الورديات",
  "Reported for Fog nodes co-located with factory floor switches.": "مُبلغ عنه لعقد Fog الموجودة بجوار محولات أرضية المصنع.",
  "Beta5G demonstrates a practical Fog–Cloud security architecture, while its current limitations define the next steps for research and deployment.": "يعرض Beta5G بنية أمنية عملية بين Fog وCloud، بينما تحدد قيوده الحالية الخطوات التالية للبحث والنشر.",
  "WHAT THE PAPER IDENTIFIES": "ما تحدده الورقة البحثية",
  "DATASET SCOPE": "نطاق مجموعة البيانات",
  "UNSW-NB15 does not contain Modbus/MQTT-specific attack vectors.": "لا تحتوي UNSW-NB15 على متجهات هجوم خاصة بـ Modbus/MQTT.",
  "OT protocol-specific attacks therefore rely on anomaly detection rather than supervised classification.": "لذلك تعتمد هجمات OT الخاصة بالبروتوكولات على كشف الشذوذ بدلًا من التصنيف الخاضع للإشراف.",
  "CLASS SIMILARITY": "تشابه الفئات",
  "XGBoost classification is constrained by similarity between some attack classes.": "يتأثر تصنيف XGBoost بالتشابه بين بعض فئات الهجوم.",
  "SHAP COMPUTATION OVERHEAD": "عبء حساب SHAP",
  "SHAP adds approximately 15–25 ms per alert at the Cloud layer under sustained high-rate attacks.": "يضيف SHAP حوالي 15–25 مللي ثانية لكل تنبيه في طبقة Cloud أثناء الهجمات المستمرة عالية المعدل.",
  "DEPLOYMENT SCALE": "نطاق النشر",
  "The current work describes a Docker-based research prototype. Future deployment should evaluate the architecture on constrained edge hardware.": "يصف العمل الحالي نموذجًا بحثيًا أوليًا قائمًا على Docker. وينبغي أن يقيّم النشر المستقبلي البنية على أجهزة Edge محدودة الموارد.",
  "WHERE BETA5G GOES NEXT": "إلى أين يتجه Beta5G بعد ذلك",
  "Evaluate the architecture with the TON_IoT dataset.": "قيّم البنية باستخدام مجموعة بيانات TON_IoT.",
  "Expand evaluation using the SWaT industrial control system dataset.": "وسّع التقييم باستخدام مجموعة بيانات نظام التحكم الصناعي SWaT.",
  "Explore WebSocket-based real-time streaming for live system communication.": "استكشف البث الآني القائم على WebSocket للاتصال الحي بالنظام.",
  "Evaluate deployment on Raspberry Pi-class Fog hardware.": "قيّم النشر على أجهزة Fog من فئة Raspberry Pi.",
  "BATCHED / ASYNCHRONOUS SHAP": "SHAP مجمع / غير متزامن",
  "Future batching or asynchronous handling could reduce queue build-up during sustained high-rate attacks.": "قد يؤدي التجميع أو التعامل غير المتزامن مستقبلًا إلى تقليل تراكم قائمة الانتظار أثناء الهجمات المستمرة عالية المعدل.",
  "CURRENT RESEARCH": "البحث الحالي",
  "BROADER DATASETS": "مجموعات بيانات أوسع",
  "REAL-TIME STREAMING": "البث الآني",
  "LIGHTWEIGHT FOG DEPLOYMENT": "نشر Fog خفيف",
  "OPTIMIZED EXPLAINABILITY": "قابلية تفسير محسنة",
  "Limitations are not gaps to hide—they define the next experiments.": "القيود ليست فجوات نخفيها، بل تحدد التجارب التالية.",
  "Beta5G is positioned as a research prototype with a clear path toward broader industrial evaluation.": "يُقدم Beta5G كنموذج بحثي أولي ذي مسار واضح نحو تقييم صناعي أوسع.",
  "Dr. Mohammed Zaki Hasan": "د. محمد زكي حسن",
  "ACADEMIC SUPERVISION · Academic Supervisor": "الإشراف الأكاديمي · المشرف الأكاديمي",
  "Academic supervision and research guidance": "الإشراف الأكاديمي والتوجيه البحثي",
  "Contact / social links placeholder": "عنصر مؤقت لروابط التواصل / الحسابات الاجتماعية",
  "TEAM LEADERSHIP · Team Leader": "قيادة الفريق · قائد الفريق",
  "RESEARCH · Research & Research Paper Writing": "البحث · البحث وكتابة الورقة البحثية",
  "SYSTEM DEVELOPMENT · Programmer / System Development": "تطوير النظام · مبرمج / تطوير النظام",
  "System development and implementation": "تطوير النظام وتنفيذه",
  "AI / CONTROL · AI / Control": "الذكاء الاصطناعي / التحكم · الذكاء الاصطناعي / التحكم",
  "Artificial intelligence and control development": "تطوير الذكاء الاصطناعي والتحكم",
  "DESIGN · Designer": "التصميم · المصمم",
  "Visual design and interface presentation": "التصميم البصري وعرض الواجهة",
  "Different disciplines. One system. One research objective.": "تخصصات مختلفة. نظام واحد. هدف بحثي واحد.",
  "From research and AI to system development and visual communication, each role contributes to the complete Beta5G prototype.": "من البحث والذكاء الاصطناعي إلى تطوير النظام والتواصل البصري، يساهم كل دور في نموذج Beta5G المتكامل.",
  "Beta5G presents a distributed Fog–Cloud intrusion detection architecture for smart factories, combining local filtering, Cloud-based classification, and explainable AI.": "يقدم Beta5G بنية موزعة لكشف التسلل بين Fog وCloud للمصانع الذكية، تجمع بين الترشيح المحلي والتصنيف القائم على Cloud والذكاء الاصطناعي القابل للتفسير.",
  "Your browser does not support HTML5 audio.": "متصفحك لا يدعم الصوت من HTML5.",
  "The project source link will be added when an official repository URL is available.": "ستُضاف وصلة مصدر المشروع عند توفر رابط مستودع رسمي.",
  "Collaborate on industrial cybersecurity, anomaly detection, Fog–Cloud architectures, and explainable AI.": "تعاون في الأمن السيبراني الصناعي وكشف الشذوذ وبنى Fog–Cloud والذكاء الاصطناعي القابل للتفسير.",
  "Explore evaluation and research opportunities in real industrial environments.": "استكشف فرص التقييم والبحث في بيئات صناعية حقيقية.",
  "Connect with the team around technical training and practical cybersecurity experience.": "تواصل مع الفريق حول التدريب التقني والخبرة العملية في الأمن السيبراني.",
  "Discuss software engineering, AI, networking, and industrial cybersecurity opportunities.": "ناقش فرص هندسة البرمجيات والذكاء الاصطناعي والشبكات والأمن السيبراني الصناعي.",
  "Open the conversation around future technical and research positions.": "افتح الحوار حول المناصب التقنية والبحثية المستقبلية."
  ,"TRAFFIC: ACTIVE": "حركة المرور: نشطة"
  ,"FOG NODE: ONLINE": "عقدة Fog: متصلة"
  ,"CLOUD: READY": "Cloud: جاهز"
  ,"XAI: READY": "XAI: جاهز"
  ,"Sensors": "المستشعرات"
  ,"Cameras": "الكاميرات"
  ,"Industrial Devices": "الأجهزة الصناعية"
  ,"Industrial Network": "الشبكة الصناعية"
  ,"SECURITY": "الأمن"
  ,"Beta5G brings together research, software engineering, artificial intelligence, systems development, and visual communication.": "يجمع Beta5G بين البحث وهندسة البرمجيات والذكاء الاصطناعي وتطوير الأنظمة والتواصل البصري.",
  "Escalated traffic → 9 attack categories": "حركة المرور المصعّدة → 9 فئات من الهجمات",
  "300 ESTIMATORS · MAX_DEPTH = 8": "300 مقدّر · max_depth = 8",
  "300 estimators · max_depth = 8": "300 مقدّر · max_depth = 8",
  "DT v3 · 99.89% recall": "DT v3 · استدعاء 99.89%",
  "XGBoost v3 · 76.15% accuracy": "XGBoost v3 · دقة 76.15%",
  "97.7% detection rate": "معدل كشف 97.7%",
  "RECALL": "الاستدعاء",
  "accuracy": "الدقة",
  "binary": "ثنائي",
  "multi": "متعدد",
  "anomaly": "شذوذ",
  "BETA5G IDS": "نظام كشف التسلل BETA5G",
  "DT v3 · Isolation Forest · XGBoost · SHAP": "DT v3 · Isolation Forest · XGBoost · SHAP"
  ,"· binary": "· ثنائي"
  ,"· multi": "· متعدد"
  ,"· anomaly": "· شذوذ"
};

const originalText = new WeakMap();
const originalAttributes = new WeakMap();

function translatePage(language) {
  const arabic = language === "ar";
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let node;
  while ((node = walker.nextNode())) {
    if (!originalText.has(node)) originalText.set(node, node.nodeValue);
    const source = originalText.get(node);
    const value = source.trim();
    if (!value) continue;
    const translated = arabic ? translations[value] : value;
    if (translated) node.nodeValue = source.replace(value, translated);
  }
  document.querySelectorAll("[aria-label]").forEach((element) => {
    if (!originalAttributes.has(element)) originalAttributes.set(element, element.getAttribute("aria-label"));
    const source = originalAttributes.get(element);
    const translated = arabic ? translations[source] : source;
    if (translated) element.setAttribute("aria-label", translated);
  });
}

function setLanguage(language) {
  const selected = language === "ar" ? "ar" : "en";
  const arabic = selected === "ar";
  document.documentElement.lang = selected;
  document.documentElement.dir = arabic ? "rtl" : "ltr";
  document.title = arabic ? "Beta5G — حماية مصنع من الهجمات السيبرانية باستخدام الذكاء الاصطناعي" : "Beta5G — Protecting a Factory from Cyberattacks Using Artificial Intelligence";
  const description = document.querySelector('meta[name="description"]');
  const ogDescription = document.querySelector('meta[property="og:description"]');
  const englishDescription = "Beta5G is a distributed, real-time intrusion detection system for smart factories focused on protecting industrial environments from cyberattacks using artificial intelligence.";
  const arabicDescription = "Beta5G هو نظام موزع وآني لكشف التسلل في المصانع الذكية يركز على حماية البيئات الصناعية من الهجمات السيبرانية باستخدام الذكاء الاصطناعي.";
  if (description) description.content = arabic ? arabicDescription : englishDescription;
  if (ogDescription) ogDescription.content = arabic ? arabicDescription : englishDescription;
  translatePage(selected);
  document.querySelectorAll("[data-language]").forEach((button) => {
    const active = button.dataset.language === selected;
    button.classList.toggle("is-active", active);
    button.setAttribute("aria-pressed", String(active));
  });
  try { localStorage.setItem("beta5g-language", selected); } catch (error) { /* Language preference is optional. */ }
}

document.addEventListener("DOMContentLoaded", () => {
  const navToggle = document.querySelector(".nav-toggle");
  const nav = document.querySelector(".main-nav");
  if (navToggle && nav) {
    const closeNav = () => {
      nav.classList.remove("is-menu-open");
      navToggle.setAttribute("aria-expanded", "false");
    };
    navToggle.addEventListener("click", () => {
      const open = !nav.classList.contains("is-menu-open");
      nav.classList.toggle("is-menu-open", open);
      navToggle.setAttribute("aria-expanded", String(open));
    });
    nav.querySelectorAll(".nav-list a, .nav-cta").forEach((link) => link.addEventListener("click", (event) => {
      closeNav();
      if (link.getAttribute("href") === "#home") {
        event.preventDefault();
        history.replaceState(null, "", "#home");
        window.scrollTo(0, 0);
      }
    }));
  }
  const demoVideo = document.querySelector(".public-v2-video video");
  const demoAudio = document.querySelector(".public-v2-video audio");
  if (demoVideo && demoAudio) {
    let syncing = false;
    const syncTime = (source, target) => {
      if (syncing || !Number.isFinite(source.currentTime)) return;
      syncing = true;
      target.currentTime = source.currentTime;
      syncing = false;
    };
    demoVideo.addEventListener("play", () => {
      syncTime(demoVideo, demoAudio);
      demoAudio.play().catch(() => {});
    });
    demoVideo.addEventListener("pause", () => demoAudio.pause());
    demoVideo.addEventListener("seeking", () => syncTime(demoVideo, demoAudio));
    demoVideo.addEventListener("timeupdate", () => {
      if (Math.abs(demoAudio.currentTime - demoVideo.currentTime) > 0.25) syncTime(demoVideo, demoAudio);
    });
    demoVideo.addEventListener("ended", () => {
      demoAudio.pause();
      demoAudio.currentTime = 0;
    });
    demoAudio.addEventListener("play", () => {
      syncTime(demoAudio, demoVideo);
      demoVideo.play().catch(() => {});
    });
    demoAudio.addEventListener("pause", () => {
      if (!demoVideo.paused) demoVideo.pause();
    });
    demoAudio.addEventListener("seeking", () => syncTime(demoAudio, demoVideo));
  }
  document.querySelectorAll("[data-language]").forEach((button) => {
    button.addEventListener("click", () => setLanguage(button.dataset.language));
  });
  let saved = "en";
  try { saved = localStorage.getItem("beta5g-language") || "en"; } catch (error) { saved = "en"; }
  setLanguage(saved);
  if (window.location.hash === "#home") setTimeout(() => window.scrollTo(0, 0), 50);
});
